version: '3.8'

services:
  backend:
    build: ./backend
    container_name: clipstream-api
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/exports:/app/exports
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis # Tunggu redis nyala dulu

  frontend:
    build: ./frontend
    container_name: clipstream-ui
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend

  # Service Baru: Redis
  redis:
    image: redis:alpine
    container_name: clipstream-redis
    ports:
      - "6379:6379"
